
meds_path: "mimic_meds_2.2"
output_path: "adjusted_mapping_full_data"
ws_name: "clmbr"
vocab_path: "athena_vocab"
metadata_path: "mapping-metadata/metadata.json"


# Stages
test: False
clean: True
subsample: False
split: True
ontology: True
preprocess: True
prepare_pretrain: False
pretrain: False
label: [
  "long_los:biased_admission_types:random_admission",
  "long_los:random_admission",
  "long_los",
  "mortality:biased_admission_types:random_admission",
  "mortality:random_admission",
  "mortality",
  "hyperlipidemia_eos",
  "hyperlipidemia_ny",
  "ckd_eos",
  "ckd_ny",
  "aki_eos",
  "aki_ny",
]
featurize: True
train_adapter: True
eval: True

test_frac: 0.15
val_frac: 0.15
slurm_config: "/home/ma/ma_ma/ma_nheilig/thesis/config/slurm_conf.yaml"
demo_mode: False
num_procs: 16

transformer:
  model: "CLMBR-T-base"