
meds_path: "/home/niclas/Dokumente/thesis-daten/mimic_meds_2.2"
output_path: "/home/niclas/Dokumente/thesis-daten/test-dir"
vocab_path: "/home/niclas/Dokumente/thesis-daten/athena_vocab"

# Stages
test: False
clean: False
subsample: False
ontology: False
#preprocess: False
label: []
label: [
  "long_los:biased_admission_types:random_admission",
  "long_los:random_admission",
  "long_los",
  "mortality:biased_admission_types:random_admission",
  "mortality:random_admission",
  "mortality",
  "hyperlipidemia_eos",
  "hyperlipidemia_ny",
  "ckd_eos",
  "ckd_ny",
  "aki_eos",
  "aki_ny",
]
split: False
featurize: False
train_adapter: False
eval: False

filter_function: "admission_length"
sample_size: 5000
reduced_size: 12000
test_frac: 0.15
val_frac: 0.15
#slurm_config: "/home/niclas/Dokumente/thesis/config/slurm_conf.yaml"
num_procs: 1